### PR TITLE
Issue/65 - Bump WordPress minimum requirements

### PR DESCRIPTION
**Pull request by dbeja**
Issue #65

**Housekeeping**

* [x] Issue number has been linked below the description
* [x] Branch name follows the `issue/###` or `release/###` format
* [x] PR title is prefixed with the branch name (issue/### - Title)

**Proposed changes**

* [x] Code has been tested with no errors
* [x] Code meets stated minimum requirements
* [x] Code should (usually) not contain unrelated changes
* [x] Code style (including docs) and organization is generally consistent with the rest of the codebase
* [x] Before and after screenshots have been posted to document visual changes
* [x] Clear steps for testing the PR have been posted (as needed)

## How to test it
1. Install and activate Checkout Referrals add-on
2. Confirm the plugin works as expected without any PHP errors.
3. Confirm existence and test saving the new settings on `Affiliates > Settings > Checkout Referrals`

### CODE REVIEW

**Review by DrewAPicture — CHANGES_REQUESTED** [review]
Looks like the vendor directory is versioned in this repo and shouldn't be. `git rm vendor` should be enough.

Also, as this is a free add-on, the "Requires at least" header in readme.txt needs to be updated as well as the changelog updated.

**Comment by dbeja** [comment]
> Looks like the vendor directory is versioned in this repo and shouldn't be. `git rm vendor` should be enough.
> 
> Also, as this is a free add-on, the "Requires at least" header in readme.txt needs to be updated as well as the changelog updated.

Shouldn't the changelog be updated only at the release PR?

**Review by DrewAPicture — CHANGES_REQUESTED** [review]
We should add `vendor/` to the gitignore and unversion the vendor files from the PR. I realize that's really kind of release-wide thing but let's just do it here.

**Comment by dbeja** [comment]
> We should add `vendor/` to the gitignore and unversion the vendor files from the PR. I realize that's really kind of release-wide thing but let's just do it here.

The vendor is already on the gitignore of this branch and vendor was already removed with `git rm -r vendor`.
Am I missing something more on this?

**Comment by DrewAPicture** [comment]
@dbeja I think I misread the changed files as _adding_ the `vendor/` files 🤦

**Review by DrewAPicture — APPROVED** [review]
Looks good.

**Pull request merged**
